export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const RESET_BURGER_BUILDER = 'RESET_BURGER_BUILDER'

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'

export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const INIT_PURCHASE = 'INIT_PURCHASE'

export const POST_ORDER_FAILED = 'POST_ORDER_FAILED'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'

export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_REDIRECT_PATH_ON_LOGIN = 'SET_REDIRECT_PATH_ON_LOGIN'

